"""Add role, password_hash, email, username, is_active to officials table

Revision ID: 008d2a1052eb
Revises: 16ac05b2e700
Create Date: 2025-09-03 18:44:17.920710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008d2a1052eb'
down_revision = '16ac05b2e700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('username')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
