"""Add type column to polling table

Revision ID: 16ac05b2e700
Revises: af0f35fc5a95
Create Date: 2025-09-03 18:16:38.380420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ac05b2e700'
down_revision = 'af0f35fc5a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
