"""Add dapil table and status_smartpol column

Revision ID: 8db831b86257
Revises: 008d2a1052eb
Create Date: 2025-09-21 17:33:37.756336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db831b86257'
down_revision = '008d2a1052eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_smartpol', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.drop_column('status_smartpol')

    # ### end Alembic commands ###
