"""Add profile columns to officials table

Revision ID: 97cfa1e87edf
Revises: 8db831b86257
Create Date: 2025-09-21 17:41:43.275979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cfa1e87edf'
down_revision = '8db831b86257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('commission_focus', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.drop_column('commission_focus')
        batch_op.drop_column('commission')
        batch_op.drop_column('education')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
