"""Initial migration with all tables

Revision ID: af0f35fc5a95
Revises: 
Create Date: 2025-09-03 18:14:09.233978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0f35fc5a95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('nik_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kecamatan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dapil', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dapil')
        batch_op.drop_column('kecamatan')
        batch_op.drop_column('nik_verified')
        batch_op.drop_column('nik')

    # ### end Alembic commands ###
