"""Add nik_prefixes column to dapil table

Revision ID: cc8b1d4c684c
Revises: 97cfa1e87edf
Create Date: 2025-09-21 18:08:05.508001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8b1d4c684c'
down_revision = '97cfa1e87edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dapil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik_prefixes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dapil', schema=None) as batch_op:
        batch_op.drop_column('nik_prefixes')

    # ### end Alembic commands ###
